---
- hosts: logproject
  gather_facts: yes
  become: yes
  roles:
  - { role: common, tags: ['common'] }

- hosts: elastic
  gather_facts: yes
  become: yes
  roles:
  - { role: elastic, tags: ['elastic'] }

- hosts: logstash
  become: yes
  roles:
  - { role: logstash, tags: ['logstash'] }
  - { role: kibana, tags: ['kibana'] }

- hosts: proxy
  become: yes
  roles:
  - { role: nginx, tags: ['nginx'] }

- hosts: app
  become: yes
  roles:
  - { role: appserver, tags: ['appserver'] }

- hosts: db
  become: yes
  roles:
  - { role: mariadb, tags: ['mariadb'] }  

- hosts: windows
  become: yes
  roles:
  - { role: winlogbeat, tags: ['winlogbeat'] }

- hosts: baseservers
  become: yes
  roles:
  - { role: packetbeat, tags: ['packetbeat'] }
  - { role: journalbeat, tags: ['journalbeat'] }
  - { role: filebeat, tags: ['filebeat'] }
  - { role: auditbeat, tags: ['auditbeat'] }




